event_list = [
u'50m hlaup',
u'50 metra grind (68 cm)',
u'50 metra grind (84 cm)',
u'50 metra grind (106.7 cm)',
u'60 metra grind (68 cm)',
u'60 metra grind (76.2 cm)',
u'60 metra grind (84 cm)',
u'60 metra grind (84.0 cm)',
u'60 metra grind (91.4 cm)',
u'60 metra grind (99.1 cm)',
u'60 metra grind (106.7cm)',
u'60 metra hlaup',
u'80 metra grind (76.2 cm)',
u'80 metra grind (84 cm)',
u'80 metra grind (91.4 cm)',
u'80 metra hlaup',
u'100 metra grind (76.2 cm)',
u'100 metra grind (84 cm)',
u'100 metra grind (91.4 cm)',
u'100 metra hlaup',
u'110 metra grind (106.7 cm)',
u'110 metra grind (91.4 cm)',
u'110 metra grind (99.1 cm)',
u'200 metra grindahlaup',
u'200 metra hlaup',
u'2000 metra hindrunarhlaup',
u'2000 metra hlaup',
u'20km brautarhlaup',
u'300 metra grind (68 cm)',
u'300 metra grind (76.2 cm)',
u'300 metra grind (84 cm)',
u'300 metra grind (91.4 cm)',
u'300 metra hlaup',
u'400 metra grind (76 cm)',
u'400 metra grind (76.2 cm)',
u'400 metra grind (84 cm)',
u'400 metra grind (91.4 cm)',
u'400 metra hlaup',
u'500 metra hlaup',
u'600 metra hlaup',
u'800 metra hlaup',
u'1000 metra boðhlaup',
u'1000 metra hlaup',
u'Hástökk',
u'Hástökk án atrennu',
u'Langstökk',
u'Langstökk án atrennu',
u'Stangarstökk',
u'Þrístökk',
u'Þrístökk án atrennu',
u'1 míla',
u'2 mílur',
u'3 km ganga',
u'10 km ganga',
u'10 km götuhlaup',
u'10 km götuhlaup (flögutímar)',
u'10.000 metra hlaup',
u'1500 metra boðhlaup',
u'1500 metra hindrunarhlaup',
u'1500 metra hlaup',
u'25 km götuhlaup',
u'3000 metra hindrunarhlaup',
u'3000 metra hlaup',
u'3000m ganga',
u'3x1500 metra boðhlaup',
u'3x800 metra boðhlaup',
u'4x100 metra boðhlaup',
u'4x1500 metra boðhlaup',
u'4x200 metra boðhlaup',
u'4x400 metra boðhlaup',
u'4x60m boðhlaup',
u'4x800 metra boðhlaup',
u'5 km ganga',
u'5 km götuhlaup',
u'5 km götuhlaup (flögutímar)',
u'5000 metra hlaup',
u'5000m ganga',
u'Boltakast',
u'Dönsk Míla (7532 metrar)',
u'Fimmtarþr. unglingastig',
u'Fimmtarþr. unglingastig 14',
u'Fimmtarþr. unglingastig 15',
u'Fimmtarþraut',
u'Fimmtarþraut (76cm grind)',
u'Fimmtarþraut (80m gr)',
u'Fimmtarþraut (meyjaáhöld)',
u'Fimmtarþraut (piltaáhöld)',
u'Fimmtarþraut (sveinaáhöld)',
u'Fimmtarþraut (telpnaáhöld)',
u'Fimmtarþraut öldunga 45',
u'Sexþraut (meyjaáhöld)',
u'Hálft maraþon',
u'Hálft maraþon (flögutímar)',
u'Kastþraut Sl.Kú.Kr.Sp.Lóð',
u'Klukkustundarhlaup',
u'Kringla 1.5kg beggja handa',
u'Kringla 1.75kg beggja handa',
u'Kringla beggja handa',
u'Kringlukast (1.0 kg)',
u'Kringlukast (1.5 kg)',
u'Kringlukast (1.6 kg)',
u'Kringlukast (1.75kg)',
u'Kringlukast (2.0 kg)',
u'Kringlukast (600g)',
u'Kringlukast (600gr)',
u'Kringlukast (750gr)',
u'Kringlukast 1kg beggja handa',
u'Kúluvarp (2.0 kg)',
u'Kúluvarp (3.0 kg)',
u'Kúluvarp (4.0 kg)',
u'Kúluvarp (4 kg)',
u'Kúluvarp (5.0 kg)',
u'Kúluvarp (5.5 kg)',
u'Kúluvarp (6.0 kg)',
u'Kúluvarp (6.00 kg)',
u'Kúluvarp (7.26 kg)',
u'Kúluvarp 3kg beggja handa',
u'Kúluvarp 4kg beggja handa',
u'Kúluvarp 5kg beggja handa',
u'Kúluvarp 6kg beggja handa',
u'Kúluvarp beggja handa',
u'Kúluvarp 7.26kg beggja handa',
u'Laugavegurinn',
u'Lóðkast (5.45 kg)',
u'Lóðkast (7.26 kg)',
u'Lóðkast (15.0 kg)',
u'Lóðkast (15.88 kg)',
u'Lóðkast (9.08 kg)',
u'Lóðkast (11.34 kg)',
u'Maraþon',
u'Maraþon (flögutímar)',
u'Fjórþraut (2kg kúla) ungl.stig',
u'Níuþraut',
u'Sjöþraut',
u'Sjöþraut (drengjaáhöld)',
u'Sjöþraut (gamla)',
u'Sjöþraut (gamla) meyjaáhöl',
u'Sjöþraut meyjaáhöld',
u'Sjöþraut stúlknaáhöld (grind)',
u'Skutlukast stelpna',
u'Skutlukast stráka',
u'Skutlukast',
u'Sleggjukast (2.0 kg)',
u'Sleggjukast (3.0 kg)',
u'Sleggjukast (4.0 kg)',
u'Sleggjukast (5.0 kg)',
u'Sleggjukast (5.5 kg)',
u'Sleggjukast (6.0 kg)',
u'Sleggjukast (6.25 kg)',
u'Sleggjukast (7.26 kg)',
u'Spjótkast (400 gr)',
u'Spjótkast (500 gr)',
u'Spjótkast (600 gr)',
u'Spjótkast (600 gr) fyrir 1997',
u'Spjótkast (700gr)',
u'Spjótkast (800 gr)',
u'Spjótkast (Fyrir 1986)',
u'Spjótkast (Fyrir 1998)',
u'Spjótkast 500g beggja handa',
u'Spjótkast 600g beggja handa',
u'Spjótkast 700g beggja handa',
u'Spjótkast 800g beggja handa',
u'Spjótkast beggja handa f. 1986',
u'Tugþraut',
u'Tugþraut 16-17 ára',
u'Tugþraut Piltar 16-17 ára',
u'Tugþraut U18 (Norðurlönd)',
u'Tugþraut U20 (Norðurlönd)',
u'Tugþraut drengjaáhöld',
u'Tugþraut sveinaáhöld',
u'Tugþraut unglingaáhöld',
u'Áttþraut (drengjaáhöld)',
u'Sjöþraut (6Kg kúla)',
u'Sjöþraut (5Kg kúla)',
u'Fimmtarþraut pilta 15 ára'
]

event_dict = {
u'50m hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'50 metra grind (68 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'50 metra grind (84 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (68 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'50 metra grind (106.7 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (76.2 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (84 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (84.0 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (91.4 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (99.1 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra grind (106.7cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'60 metra hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'80 metra grind (76.2 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'80 metra grind (84 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'80 metra grind (91.4 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'80 metra hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'100 metra grind (76.2 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'100 metra grind (84 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'100 metra grind (91.4 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'100 metra hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'110 metra grind (106.7 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'110 metra grind (91.4 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'110 metra grind (99.1 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'200 metra grindahlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'200 metra hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'2000 metra hindrunarhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'2000 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'20km brautarhlaup': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'300 metra grind (68 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'300 metra grind (76.2 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'300 metra grind (84 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'300 metra grind (91.4 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'300 metra hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'400 metra grind (76 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'400 metra grind (76.2 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'400 metra grind (84 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'400 metra grind (91.4 cm)': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'400 metra hlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'500 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'600 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'800 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'1000 metra boðhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'1000 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'Hástökk': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Hástökk án atrennu': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Langstökk': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': True},
u'Langstökk án atrennu': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Stangarstökk': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': True},
u'Þrístökk': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': True},
u'Þrístökk án atrennu': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'1 míla': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'2 mílur': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'3 km ganga': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'10 km ganga': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'10 km götuhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'10 km götuhlaup (flögutímar)': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'10.000 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'1500 metra boðhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'1500 metra hindrunarhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'1500 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'25 km götuhlaup': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'3000 metra hindrunarhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'3000 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'3000m ganga': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'3x1500 metra boðhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'3x800 metra boðhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'4x100 metra boðhlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'4x1500 metra boðhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'4x200 metra boðhlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'4x400 metra boðhlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'4x60m boðhlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'4x800 metra boðhlaup': {'UNIT': 's', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'5 km ganga': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'5 km götuhlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'5 km götuhlaup (flögutímar)': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'5000 metra hlaup': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'5000m ganga': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': False, 'WIND': True},
u'Boltakast': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': True},
u'Dönsk Míla (7532 metrar)': {'UNIT': 'M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'Fimmtarþr. unglingastig': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþr. unglingastig 14': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþr. unglingastig 15': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut (76cm grind)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut (80m gr)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut (meyjaáhöld)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut (piltaáhöld)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut (sveinaáhöld)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut (telpnaáhöld)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut öldunga 45': {'UNIT': 's', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sexþraut (meyjaáhöld)': {'UNIT': 's', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Hálft maraþon': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'Hálft maraþon (flögutímar)': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'Kastþraut Sl.Kú.Kr.Sp.Lóð': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Klukkustundarhlaup': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringla 1.5kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringla 1.75kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringla beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (1.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (1.5 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (1.6 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (1.75kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (2.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (600g)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (600gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast (750gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kringlukast 1kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (2.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (3.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (4.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (4 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (5.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (5.5 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (6.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (6.00 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp (7.26 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp 3kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp 4kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp 5kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp 6kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Kúluvarp 7.26kg beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Laugavegurinn': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': False, 'WIND': False},
u'Lóðkast (5.45 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Lóðkast (7.26 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Lóðkast (15.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Lóðkast (15.88 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Lóðkast (9.08 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Lóðkast (11.34 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Maraþon': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'Maraþon (flögutímar)': {'UNIT': 'H:M:S', 'MAX': False, 'TIME_AXIS': True, 'WIND': False},
u'Fjórþraut (2kg kúla) ungl.stig': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Níuþraut': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut (drengjaáhöld)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut (gamla)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut (gamla) meyjaáhöl': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut meyjaáhöld': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut stúlknaáhöld (grind)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut (6Kg kúla)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sjöþraut (5Kg kúla)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Skutlukast stelpna': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Skutlukast stráka': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Skutlukast': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (2.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (3.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (4.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (5.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (5.5 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (6.0 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (6.25 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Sleggjukast (7.26 kg)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (400 gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (500 gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (600 gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (600 gr) fyrir 1997': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (700gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (800 gr)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (Fyrir 1986)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast (Fyrir 1998)': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast 500g beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast 600g beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast 700g beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast 800g beggja handa': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Spjótkast beggja handa f. 1986': {'UNIT': 'm', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut 16-17 ára': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut Piltar 16-17 ára': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut U18 (Norðurlönd)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut U20 (Norðurlönd)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut drengjaáhöld': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut sveinaáhöld': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Tugþraut unglingaáhöld': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Áttþraut (drengjaáhöld)': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False},
u'Fimmtarþraut pilta 15 ára': {'UNIT': 'Stig', 'MAX': True, 'TIME_AXIS': False, 'WIND': False}
}
