providers = ["...", "python"]

[phases.setup]
nixPkgs = ['...', 'nginx']

[phases.build]
cmd = ['npm run build', 'pip install -r requirements.txt', 'mkdir -p /app/logs/nginx']

[start]
cmd = '(echo "Starting gunicorn"); (gunicorn -c /app/config/gunicorn.conf.py Sif.wsgi &); (sleep 2); (echo "Starting nginx"); nginx -c /app/config/nginx.conf'