services:
# A Python Django service for the backend
  - type: web
    name: Sif-Django-Backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    rootDir: backend
    autoDeploy: true
    region: frankfurt
    repo: https://github.com/frjalsar/afrekaskra
    branch: render
    numInstances: 1
    envVars:
      - key: PORT
        value: 8000
      - key: SIF_ON_RENDER
        value: 1
      - key: SIF_DB_PASSWORD
        sync: false
      - key: SIF_DB_USER
        sync: false
      - key: SIF_DB_HOST
        sync: false
      - key: SIF_DB_PORT
        sync: false
      - key: SIF_DB_NAME
        sync: false
      - key: SIF_REDIS_URL
        sync: false
      - key: SIF_SECRET_KEY
        generateValue: true

# A static Vue site for the frontend
  - type: web
    name: Sif-Vue-Frontend
    runtime: static
    rootDir: frontend
    autoDeploy: true
    repo: https://github.com/frjalsar/afrekaskra
    branch: render
    #plan: starter
    buildCommand: npm run build
    staticPublishPath: ./dist
    domains:
      - afrek.fri.is
      - afrekaskra.fri.is
      - sif.fri.is
#    headers:
#      - path: /*
#        name: X-Frame-Options
#        value: sameorigin
    routes:
# Rewrite /api/* to the backend service
      - type: rewrite
        source: /api/*
        destination: https://sif-django-backend-fhh0.onrender.com/api/*
# Note: /api/* does not match /api
      - type: rewrite
        source: /api
        destination: https://sif-django-backend-fhh0.onrender.com/api/
# Rewrite all other paths to index.html for Vue Router
      - type: rewrite
        source: /*
        destination: /index.html

# A Redis cache for the site
  - type: redis
    name: Sif-Redis-Cache
    plan: free
    region: frankfurt
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []