services:
# A Python FastAPI service for the backend
  - type: web
    name: Sif-Django-Backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    rootDir: backend
    autoDeploy: true
    region: frankfurt
    repo: https://github.com/frjalsar/afrekaskra
    branch: render
    numInstances: 1
    envVars:
      - key: SIF_ON_RENDER
        value: 1
      - key: SIF_DB_PASSWORD
        sync: false
      - key: SIF_DB_USER
        sync: false
      - key: SIF_SECRET_KEY
        generateValue: true

# A static Vue site for the frontend
  - type: web
    name: Sif-Vue-Frontend
    runtime: static
    rootDir: frontend
    autoDeploy: true
    repo: https://github.com/frjalsar/afrekaskra
    branch: render
    #plan: starter
    buildCommand: npm run build
    staticPublishPath: ./dist
#    headers:
#      - path: /*
#        name: X-Frame-Options
#        value: sameorigin
    routes:
# Rewrite /api/* to the backend service
      - type: rewrite
        source: /api/*
        destination: https://sif-django-backend.onrender.com/*
# Note: /api/* does not match /api
      - type: rewrite
        source: /api
        destination: https://sif-django-backend.onrender.com/
# Rewrite all other paths to index.html for Vue Router
      - type: rewrite
        source: /*
        destination: /index.html